# Generated by Django 4.0.1 on 2023-07-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230301_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
