# Generated by Django 4.0.1 on 2023-07-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nacional',
            field=models.BooleanField(default=True),
        ),
    ]
