# Generated by Django 4.0.1 on 2023-08-07 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_nacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('longitud', models.DecimalField(decimal_places=60, max_digits=100)),
                ('latitud', models.DecimalField(decimal_places=60, max_digits=100)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('img1', models.ImageField(blank=True, null=True, upload_to='actividad_images')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='actividad_images')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_interes', models.DateField()),
                ('idactividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.actividad')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.actividadtipo'),
        ),
    ]
