# Generated by Django 4.0.1 on 2023-08-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_tipoevento_remove_actividad_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='img1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='img2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
